apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "infinispan.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "infinispan.name" . }}
    helm.sh/chart: {{ include "infinispan.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    helm.sh/hook: pre-install
