kind: Service
apiVersion: v1
metadata:
  name: infinispan-sitea-external
  namespace: infinispan-operator
  labels:
    app: infinispan-service-external
    clusterName: infinispan-sitea
    infinispan_cr: infinispan-sitea
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
spec:
  ports:
    - protocol: TCP
      port: 11222
      targetPort: 11222
      nodePort: 31403
  selector:
    app: infinispan-pod
    clusterName: infinispan-sitea
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster