# Default values for infinispan.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # repository is the Infinispan image name
  repository_op: docker.io/yogeshwar94/infi-server
  tag_op: "12.4 "

  repository_server: infinispan/server
  tag_server: "12.1"
 
remotesite:
 name: sitea
 nodeport: 32556
 publicIP: 35.226.80.2
 secretName: siteatoken
 
site:
 name: siteb
 nodeport: 32556
 publicIP: 35.239.160.183
 secretName: sitebtoken
#
resources: {}
  # limits:
  #  cpu: "0.5"
  #  memory: 512Mi
  # requests:
  #  cpu: "0.5"
  #  memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
