apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "infinispan.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "infinispan.name" . }}
    helm.sh/chart: {{ include "infinispan.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    helm.sh/hook: pre-install
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "infinispan.name" . }}
  template:
    metadata:
      labels:
       app.kubernetes.io/name: {{ include "infinispan.name" . }}
       helm.sh/chart: {{ include "infinispan.chart" . }}
       app.kubernetes.io/instance: {{ .Release.Name }}
       app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      serviceAccountName: {{ include "infinispan.name" . }}-operator
      securityContext:
        runAsUser: 2500
        fsGroup: 2000
      containers:
        - name: {{ include "infinispan.name" . }}
          image: {{ .Values.image.repository_op }}:{{ .Values.image.tag_op }}
          securityContext:
            allowPrivilegeEscalation: false
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - infinispan-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "infinispan-operator"
            - name: DEFAULT_IMAGE
              value: "{{ .Values.image.repository_server }}:{{ .Values.image.tag_server }}"
            - name: MAKE_DATADIR_WRITABLE
              value: 'true'
